# 🐱 CONFIGURACIÓN TOMCAT AMAZON LINUX
# Config Server - application-tomcat.yml

server:
  # External access para AWS EC2
  address: 0.0.0.0
  port: 8888
  
  # Configuración Tomcat específica
  tomcat:
    accept-count: 100
    max-connections: 10000
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-http-form-post-size: 2MB
    
  # Compression para mejor performance
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
  # SSL termination en ELB
  forward-headers-strategy: native

spring:
  application:
    name: config-server
    
  # Solo profile AWS necesario
  profiles:
    active: aws
    
  # Cloud Config Server configuración
  cloud:
    config:
      server:
        git:
          uri: file:/opt/tomcat-instances/config-repository
          default-label: main
        native:
          search-locations: file:/opt/tomcat-instances/config-repository
      enabled: true
      
  # Security básica
  security:
    user:
      name: admin
      password: ${CONFIG_SERVER_PASSWORD:arkaconfigpass2024}
      
# Eureka Client Configuration
eureka:
  instance:
    # AWS EC2 public IP
    hostname: ${AWS_PUBLIC_IP:18.117.120.169}
    prefer-ip-address: true
    ip-address: ${AWS_PUBLIC_IP:18.117.120.169}
    instance-id: ${spring.application.name}:${AWS_PUBLIC_IP:18.117.120.169}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://${AWS_PUBLIC_IP:18.117.120.169}:8761/eureka/
    registry-fetch-interval-seconds: 5
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  server:
    address: 0.0.0.0
    port: 8888
    
# Logging para Tomcat
logging:
  level:
    com.arkavalenzuela: INFO
    org.springframework.cloud.config: INFO
    org.springframework.security: WARN
    com.netflix.eureka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: /opt/tomcat-instances/logs/config-server.log
    max-size: 10MB
    max-history: 30